#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

echo
echo "======================================"
echo "        Archivyn Installation"
echo "======================================"
echo

if ! command -v docker >/dev/null 2>&1; then
    echo "Error: Docker is not installed."
    exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
    echo "Error: Docker Compose is not available."
    exit 1
fi

if [[ -f "$ENV_FILE" ]]; then
    echo "An existing .env file was found."
    read -r -p "Use the existing configuration? [Y/n]: " USE_EXISTING
    USE_EXISTING="${USE_EXISTING:-Y}"

    if [[ "$USE_EXISTING" =~ ^[Yy]$ ]]; then
        echo "Using existing configuration."
        docker compose up -d --build
        docker compose ps
        exit 0
    fi

    BACKUP_FILE=".env.backup.$(date +%Y%m%d-%H%M%S)"
    cp "$ENV_FILE" "$BACKUP_FILE"
    echo "Existing configuration backed up to $BACKUP_FILE"
fi

read -r -p "Archivyn web port [17421]: " ARCHIVYN_PORT
ARCHIVYN_PORT="${ARCHIVYN_PORT:-17421}"

read -r -p "PostgreSQL database [archivyn]: " POSTGRES_DB
POSTGRES_DB="${POSTGRES_DB:-archivyn}"

read -r -p "PostgreSQL username [archivyn]: " POSTGRES_USER
POSTGRES_USER="${POSTGRES_USER:-archivyn}"

echo
read -r -s -p "PostgreSQL password (leave blank to generate one): " POSTGRES_PASSWORD
echo

if [[ -z "$POSTGRES_PASSWORD" ]]; then
    if command -v openssl >/dev/null 2>&1; then
        POSTGRES_PASSWORD="$(openssl rand -hex 32)"
    else
        POSTGRES_PASSWORD="$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 48)"
    fi

    PASSWORD_GENERATED=true
else
    PASSWORD_GENERATED=false
fi

if [[ "$POSTGRES_PASSWORD" == *$'\n'* ]] || [[ "$POSTGRES_PASSWORD" == *$'\r'* ]]; then
    echo "Error: The password cannot contain line breaks."
    exit 1
fi

cat > "$ENV_FILE" <<EOF
# Generated by the Archivyn installer.
# Do not commit this file.

ARCHIVYN_PORT=${ARCHIVYN_PORT}

POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
EOF

chmod 600 "$ENV_FILE"

echo
echo "Configuration written to:"
echo "  $ENV_FILE"
echo

if [[ "$PASSWORD_GENERATED" == true ]]; then
    echo "Generated PostgreSQL password:"
    echo
    echo "  $POSTGRES_PASSWORD"
    echo
    echo "Store this password somewhere secure."
    echo
fi

echo "Building and starting Archivyn..."
docker compose up -d --build

echo
docker compose ps

echo
echo "Archivyn installation completed."
echo "Open:"
echo
echo "  http://SERVER-IP:${ARCHIVYN_PORT}"
echo