// <auto-generated />
using Archivyn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Archivyn.Migrations
{
    [DbContext(typeof(ArchivynDbContext))]
    [Migration("20260805013824_AddGlobalSystemKeywords")]
    partial class AddGlobalSystemKeywords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Archivyn.Models.DocumentType", b =>
                {
                    b.Property<long>("ItemTypeNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("itemtypenum");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemTypeNum"));

                    b.Property<string>("AutoNameString")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("autonamestring");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("ItemTypeGroupNum")
                        .HasColumnType("bigint")
                        .HasColumnName("itemtypegroupnum");

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("itemtypename");

                    b.HasKey("ItemTypeNum");

                    b.HasIndex("ItemTypeGroupNum");

                    b.HasIndex("ItemTypeName")
                        .IsUnique();

                    b.ToTable("DOCTYPE", (string)null);

                    b.HasData(
                        new
                        {
                            ItemTypeNum = 1L,
                            IsSystem = true,
                            ItemTypeGroupNum = 1L,
                            ItemTypeName = "Unindexed"
                        });
                });

            modelBuilder.Entity("Archivyn.Models.DocumentTypeKeyType", b =>
                {
                    b.Property<long>("ItemTypeNum")
                        .HasColumnType("bigint")
                        .HasColumnName("itemtypenum");

                    b.Property<long>("KeyTypeNum")
                        .HasColumnType("bigint")
                        .HasColumnName("keytypenum");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("ItemTypeNum", "KeyTypeNum");

                    b.HasIndex("KeyTypeNum");

                    b.HasIndex("ItemTypeNum", "DisplayOrder");

                    b.ToTable("DOCTYPEKEYTYPE", (string)null);

                    b.HasData(
                        new
                        {
                            ItemTypeNum = 1L,
                            KeyTypeNum = 2L,
                            DisplayOrder = 2,
                            IsRequired = true,
                            IsSystem = true
                        });
                });

            modelBuilder.Entity("Archivyn.Models.DocumentTypeKeywordTypeGroup", b =>
                {
                    b.Property<long>("ItemTypeNum")
                        .HasColumnType("bigint")
                        .HasColumnName("itemtypenum");

                    b.Property<long>("KeySetTableNum")
                        .HasColumnType("bigint")
                        .HasColumnName("keysettablenum");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("ItemTypeNum", "KeySetTableNum");

                    b.HasIndex("KeySetTableNum");

                    b.HasIndex("ItemTypeNum", "DisplayOrder");

                    b.ToTable("DOCTYPEKEYTYPEGROUP", (string)null);
                });

            modelBuilder.Entity("Archivyn.Models.ItemTypeGroup", b =>
                {
                    b.Property<long>("ItemTypeGroupNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("itemtypegroupnum");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemTypeGroupNum"));

                    b.Property<long>("Flags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("flags");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemTypeGroupName")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("itemtypegroupname");

                    b.HasKey("ItemTypeGroupNum");

                    b.HasIndex("ItemTypeGroupName")
                        .IsUnique();

                    b.ToTable("ITEMTYPEGROUP", (string)null);

                    b.HasData(
                        new
                        {
                            ItemTypeGroupNum = 1L,
                            Flags = 0L,
                            IsSystem = true,
                            ItemTypeGroupName = "System Documents"
                        });
                });

            modelBuilder.Entity("Archivyn.Models.KeyType", b =>
                {
                    b.Property<long>("KeyTypeNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("keytypenum");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KeyTypeNum"));

                    b.Property<bool>("AddToAllDocumentTypes")
                        .HasColumnType("boolean");

                    b.Property<int>("AllDocumentTypesDisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("DataType")
                        .HasColumnType("integer")
                        .HasColumnName("datatype");

                    b.Property<bool>("IsRequiredOnAllDocumentTypes")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<long>("KeyTypeLen")
                        .HasColumnType("bigint")
                        .HasColumnName("keytypelen");

                    b.Property<string>("KeyTypeName")
                        .IsRequired()
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("keytypename");

                    b.HasKey("KeyTypeNum");

                    b.HasIndex("KeyTypeName")
                        .IsUnique();

                    b.ToTable("KEYTYPETABLE", (string)null);

                    b.HasData(
                        new
                        {
                            KeyTypeNum = 1L,
                            AddToAllDocumentTypes = true,
                            AllDocumentTypesDisplayOrder = 1,
                            DataType = 3,
                            IsRequiredOnAllDocumentTypes = true,
                            IsSystem = true,
                            KeyTypeLen = 10L,
                            KeyTypeName = ">> Document Date"
                        },
                        new
                        {
                            KeyTypeNum = 2L,
                            AddToAllDocumentTypes = true,
                            AllDocumentTypesDisplayOrder = 2,
                            DataType = 1,
                            IsRequiredOnAllDocumentTypes = false,
                            IsSystem = false,
                            KeyTypeLen = 250L,
                            KeyTypeName = "Description"
                        });
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSet", b =>
                {
                    b.Property<long>("KeySetTableNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("keysettablenum");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KeySetTableNum"));

                    b.Property<long>("Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("flags");

                    b.Property<long>("IsKeyTypeGroup")
                        .HasColumnType("bigint")
                        .HasColumnName("iskeytypegroup");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KeySetName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("keysetname");

                    b.HasKey("KeySetTableNum");

                    b.HasIndex("KeySetName")
                        .IsUnique();

                    b.ToTable("KEYWORDSET", (string)null);
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSetKeyType", b =>
                {
                    b.Property<long>("KeySetTableNum")
                        .HasColumnType("bigint")
                        .HasColumnName("keysettablenum");

                    b.Property<long>("KeyTypeNum")
                        .HasColumnType("bigint")
                        .HasColumnName("keytypenum");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("KeySetTableNum", "KeyTypeNum");

                    b.HasIndex("KeyTypeNum");

                    b.HasIndex("KeySetTableNum", "DisplayOrder");

                    b.ToTable("KEYWORDSETKEYTYPE", (string)null);
                });

            modelBuilder.Entity("Archivyn.Models.DocumentType", b =>
                {
                    b.HasOne("Archivyn.Models.ItemTypeGroup", "ItemTypeGroup")
                        .WithMany("DocumentTypes")
                        .HasForeignKey("ItemTypeGroupNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemTypeGroup");
                });

            modelBuilder.Entity("Archivyn.Models.DocumentTypeKeyType", b =>
                {
                    b.HasOne("Archivyn.Models.DocumentType", "DocumentType")
                        .WithMany("KeywordTypeAssignments")
                        .HasForeignKey("ItemTypeNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archivyn.Models.KeyType", "KeyType")
                        .WithMany("DocumentTypeAssignments")
                        .HasForeignKey("KeyTypeNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("KeyType");
                });

            modelBuilder.Entity("Archivyn.Models.DocumentTypeKeywordTypeGroup", b =>
                {
                    b.HasOne("Archivyn.Models.DocumentType", "DocumentType")
                        .WithMany("KeywordTypeGroupAssignments")
                        .HasForeignKey("ItemTypeNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archivyn.Models.KeywordSet", "KeywordTypeGroup")
                        .WithMany("DocumentTypeAssignments")
                        .HasForeignKey("KeySetTableNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("KeywordTypeGroup");
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSetKeyType", b =>
                {
                    b.HasOne("Archivyn.Models.KeywordSet", "KeywordSet")
                        .WithMany("KeywordTypeMemberships")
                        .HasForeignKey("KeySetTableNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archivyn.Models.KeyType", "KeyType")
                        .WithMany("KeywordSetMemberships")
                        .HasForeignKey("KeyTypeNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyType");

                    b.Navigation("KeywordSet");
                });

            modelBuilder.Entity("Archivyn.Models.DocumentType", b =>
                {
                    b.Navigation("KeywordTypeAssignments");

                    b.Navigation("KeywordTypeGroupAssignments");
                });

            modelBuilder.Entity("Archivyn.Models.ItemTypeGroup", b =>
                {
                    b.Navigation("DocumentTypes");
                });

            modelBuilder.Entity("Archivyn.Models.KeyType", b =>
                {
                    b.Navigation("DocumentTypeAssignments");

                    b.Navigation("KeywordSetMemberships");
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSet", b =>
                {
                    b.Navigation("DocumentTypeAssignments");

                    b.Navigation("KeywordTypeMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
