// <auto-generated />
using Archivyn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Archivyn.Migrations
{
    [DbContext(typeof(ArchivynDbContext))]
    partial class ArchivynDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Archivyn.Models.KeyType", b =>
                {
                    b.Property<long>("KeyTypeNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("keytypenum");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KeyTypeNum"));

                    b.Property<long>("DataType")
                        .HasColumnType("bigint")
                        .HasColumnName("datatype");

                    b.Property<long>("KeyTypeFlags")
                        .HasColumnType("bigint")
                        .HasColumnName("keytypeflags");

                    b.Property<long>("KeyTypeLen")
                        .HasColumnType("bigint")
                        .HasColumnName("keytypelen");

                    b.Property<string>("KeyTypeMask")
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("keytypemask");

                    b.Property<string>("KeyTypeName")
                        .IsRequired()
                        .HasMaxLength(51)
                        .HasColumnType("character varying(51)")
                        .HasColumnName("keytypename");

                    b.HasKey("KeyTypeNum");

                    b.HasIndex("KeyTypeName")
                        .IsUnique();

                    b.ToTable("KEYTYPETABLE", (string)null);
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSet", b =>
                {
                    b.Property<long>("KeySetTableNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("keysettablenum");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("KeySetTableNum"));

                    b.Property<long>("Flags")
                        .HasColumnType("bigint")
                        .HasColumnName("flags");

                    b.Property<long>("IsKeyTypeGroup")
                        .HasColumnType("bigint")
                        .HasColumnName("iskeytypegroup");

                    b.Property<string>("KeySetName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("keysetname");

                    b.HasKey("KeySetTableNum");

                    b.HasIndex("KeySetName")
                        .IsUnique();

                    b.ToTable("KEYWORDSET", (string)null);
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSetKeyType", b =>
                {
                    b.Property<long>("KeySetTableNum")
                        .HasColumnType("bigint")
                        .HasColumnName("keysettablenum");

                    b.Property<long>("KeyTypeNum")
                        .HasColumnType("bigint")
                        .HasColumnName("keytypenum");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("displayorder");

                    b.HasKey("KeySetTableNum", "KeyTypeNum");

                    b.HasIndex("KeyTypeNum");

                    b.HasIndex("KeySetTableNum", "DisplayOrder");

                    b.ToTable("KEYWORDSETKEYTYPE", (string)null);
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSetKeyType", b =>
                {
                    b.HasOne("Archivyn.Models.KeywordSet", "KeywordSet")
                        .WithMany("KeywordTypeMemberships")
                        .HasForeignKey("KeySetTableNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Archivyn.Models.KeyType", "KeyType")
                        .WithMany("KeywordSetMemberships")
                        .HasForeignKey("KeyTypeNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyType");

                    b.Navigation("KeywordSet");
                });

            modelBuilder.Entity("Archivyn.Models.KeyType", b =>
                {
                    b.Navigation("KeywordSetMemberships");
                });

            modelBuilder.Entity("Archivyn.Models.KeywordSet", b =>
                {
                    b.Navigation("KeywordTypeMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
